Reverting the r523 change for parens matching <!() expansions.  It breaks the following test case:
{
  'conditions': [
    ['OS=="linux"', {
      'targets': [
        {
          'target_name': 'foo',
          'target_type': 'none',
          'variables': {
            'host_arch': '<!(echo command_not_found)',
          },
        },
      ],
    }],
  ],
}

With the following traceback:

/bin/sh: command_not_found: command not found
Traceback (most recent call last):
  File "gyp", line 14, in <module>
    sys.exit(gyp.main(sys.argv[1:]))
  File "/usr/lib/python2.5/site-packages/PIL/__init__.py", line 200, in main
    
  File "/usr/lib/python2.5/site-packages/PIL/__init__.py", line 57, in Load
    
  File "pylib/gyp/input.py", line 1606, in Load
    LoadTargetBuildFile(build_file, data, aux_data, variables, includes, depth)
  File "pylib/gyp/input.py", line 239, in LoadTargetBuildFile
    build_file_path)
  File "pylib/gyp/input.py", line 657, in ProcessVariablesAndConditionsInDict
    build_file)
  File "pylib/gyp/input.py", line 673, in ProcessVariablesAndConditionsInList
    build_file)
  File "pylib/gyp/input.py", line 574, in ProcessVariablesAndConditionsInDict
    variables.copy(), build_file)
  File "pylib/gyp/input.py", line 581, in ProcessVariablesAndConditionsInDict
    expanded = ExpandVariables(value, is_late, variables, build_file)
  File "pylib/gyp/input.py", line 389, in ExpandVariables
    raise subprocess.CalledProcessError(p.returncode, command)
subprocess.CalledProcessError: Command 'command_not_found' returned non-zero exit status 127

So something in the nested condition is apparently making it try to
re-execute the output from the <!() as a command itself...

BUG=none
TEST=none
Review URL: http://codereview.chromium.org/132077