Add backported OrderedDict
Using collections.OrderedDict caused chromium roll to fail:

Broke Win Builder (dbg) runhooks:

  File
"C:\b\build\slave\cr-win-dbg\build\src\tools\gyp\pylib\gyp\generator\msvs.py",
line 223, in _ConvertSourcesToFilterHierarchy
      folders = collections.OrderedDict()
  AttributeError: 'module' object has no attribute 'OrderedDict'

R=thakis@chromium.org
BUG=241769

Review URL: https://codereview.chromium.org/106233005